# Generated by Django 3.2.8 on 2024-06-27 07:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20240615_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ'),
        ),
    ]
