# Generated by Django 3.2.8 on 2024-06-27 07:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_alter_questions_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpage',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='keywords_en',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='keywords_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='keywords_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='page_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='page_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='page_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок SEO'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок SEO'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок SEO'),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_en',
            field=models.TextField(null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_ky',
            field=models.TextField(null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_ru',
            field=models.TextField(null=True, verbose_name='Вопрос'),
        ),
    ]
