# Generated by Django 3.2.8 on 2024-07-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_auto_20240627_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='show_main_page',
            field=models.BooleanField(blank=True, default=False, verbose_name='Отображать на главной странице'),
        ),
    ]
