# Generated by Django 3.2.8 on 2024-07-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_questions_show_main_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpage',
            name='link',
            field=models.URLField(default=1, verbose_name='Ссылка на опросник'),
            preserve_default=False,
        ),
    ]
