# Generated by Django 3.2.8 on 2024-06-15 13:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import toyboss.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок SEO')),
                ('description', models.TextField(blank=True, verbose_name='Описание SEO')),
                ('keywords', models.TextField(blank=True, verbose_name='Ключевые слова SEO')),
                ('page_title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('page_subtitle', models.TextField(verbose_name='Подзаголовок страницы')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='SocialItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(help_text='Формат файла: SVG. Ограничение размера: 1 Мбайт.', upload_to=toyboss.functions.get_file_path, validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Иконка социальной сети')),
                ('link', models.URLField(verbose_name='Ссылка социальной сети')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_items', to='contacts.socialnetwork')),
            ],
            options={
                'verbose_name': 'Иконки и ссылки социальных сетей',
                'verbose_name_plural': 'Иконки и ссылки социальных сетей',
            },
        ),
    ]
