# Generated by Django 3.2.8 on 2024-06-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_marketingdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_department_title', models.CharField(max_length=255, verbose_name='Отдел производства')),
                ('production_department_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('production_department_phone', models.CharField(max_length=255, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Отдел производства',
                'verbose_name_plural': 'Отдел производства',
            },
        ),
    ]
