# Generated by Django 3.2.8 on 2024-06-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_productiondepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_department_title', models.CharField(max_length=255, verbose_name='Бухгалтерия')),
                ('accounting_department_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('accounting_department_phone', models.CharField(max_length=255, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Бухгалтерия',
                'verbose_name_plural': 'Бухгалтерия',
            },
        ),
    ]
