# Generated by Django 3.2.8 on 2024-06-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_accounting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('central_office_title', models.CharField(max_length=255, verbose_name='Центральный офис')),
                ('central_office_address', models.TextField(verbose_name='Адрес центрального офиса')),
            ],
            options={
                'verbose_name': 'Центральный офис',
                'verbose_name_plural': 'Центральный офис',
            },
        ),
        migrations.CreateModel(
            name='CorporateOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_office_title', models.CharField(max_length=255, verbose_name='Корпоративный офис')),
                ('corporate_office_address', models.TextField(verbose_name='Адрес корпоративного офиса')),
            ],
            options={
                'verbose_name': 'Корпоративный офис',
                'verbose_name_plural': 'Корпоративный офис',
            },
        ),
    ]
