# Generated by Django 3.2.8 on 2024-07-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20240701_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='dinner_hours',
            field=models.CharField(default=1, max_length=255, verbose_name='Часы работы в обед'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='monday_friday_hours',
            field=models.CharField(default=1, max_length=255, verbose_name='Часы работы в понедельник - пятница'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='saturday_hours',
            field=models.CharField(default=1, max_length=255, verbose_name='Часы работы в субботу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday_friday',
            field=models.CharField(max_length=255, verbose_name='Понедельник - пятница'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday_friday_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Понедельник - пятница'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday_friday_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Понедельник - пятница'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday_friday_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Понедельник - пятница'),
        ),
    ]
