# Generated by Django 3.2.8 on 2024-07-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20240701_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingdepartment',
            name='marketing_department_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Отдел маркетинга'),
        ),
        migrations.AddField(
            model_name='marketingdepartment',
            name='marketing_department_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Отдел маркетинга'),
        ),
        migrations.AddField(
            model_name='marketingdepartment',
            name='marketing_department_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Отдел маркетинга'),
        ),
    ]
