# Generated by Django 3.2.8 on 2024-07-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20240701_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='accounting_department_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Бухгалтерия'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='accounting_department_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Бухгалтерия'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='accounting_department_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Бухгалтерия'),
        ),
    ]
