# Generated by Django 3.2.8 on 2024-07-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_auto_20240701_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateoffice',
            name='corporate_office_address_en',
            field=models.TextField(null=True, verbose_name='Адрес корпоративного офиса'),
        ),
        migrations.AddField(
            model_name='corporateoffice',
            name='corporate_office_address_ky',
            field=models.TextField(null=True, verbose_name='Адрес корпоративного офиса'),
        ),
        migrations.AddField(
            model_name='corporateoffice',
            name='corporate_office_address_ru',
            field=models.TextField(null=True, verbose_name='Адрес корпоративного офиса'),
        ),
        migrations.AddField(
            model_name='corporateoffice',
            name='corporate_office_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Корпоративный офис'),
        ),
        migrations.AddField(
            model_name='corporateoffice',
            name='corporate_office_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Корпоративный офис'),
        ),
        migrations.AddField(
            model_name='corporateoffice',
            name='corporate_office_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Корпоративный офис'),
        ),
    ]
