# Generated by Django 3.2.8 on 2024-07-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_auto_20240701_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='saturday_en',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='saturday_hours',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='saturday_ky',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='saturday_ru',
        ),
    ]
