# Generated by Django 3.2.8 on 2024-07-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_auto_20240704_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounting',
            options={'verbose_name': 'По другим вопросам', 'verbose_name_plural': 'По другим вопросам'},
        ),
    ]
