# Generated by Django 3.2.8 on 2024-07-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_alter_accounting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centraloffice',
            options={'verbose_name': 'Производственный завод и главный офис', 'verbose_name_plural': 'Производственный завод и главный офис'},
        ),
    ]
