# Generated by Django 3.2.8 on 2024-07-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_alter_centraloffice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporateoffice',
            options={'verbose_name': 'Офис отдела продаж и маркетинга', 'verbose_name_plural': 'Офис отдела продаж и маркетинга'},
        ),
    ]
