# Generated by Django 3.2.8 on 2024-07-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_alter_corporateoffice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketingdepartment',
            options={'verbose_name': 'Предложения и обратная связь', 'verbose_name_plural': 'Предложения и обратная связь'},
        ),
    ]
