# Generated by Django 3.2.8 on 2024-07-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_alter_marketingdepartment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productiondepartment',
            options={'verbose_name': 'Отдел кадров', 'verbose_name_plural': 'Отдел кадров'},
        ),
    ]
