# Generated by Django 3.2.8 on 2024-07-04 16:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_alter_productiondepartment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='rules',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Условия соглашения'),
        ),
    ]
