# Generated by Django 3.2.8 on 2024-07-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_alter_contactform_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='position',
        ),
    ]
