# Generated by Django 3.2.8 on 2024-09-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0026_auto_20240923_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='email_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Ваш email'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='email_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Ваш email'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='email_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ваш email'),
        ),
    ]
