# Generated by Django 3.2.8 on 2024-09-23 11:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0027_auto_20240923_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='rules_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Условия соглашения'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='rules_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Условия соглашения'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='rules_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Условия соглашения'),
        ),
    ]
