# Generated by Django 3.2.8 on 2024-06-15 13:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import toyboss.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('keywords', models.TextField(blank=True, verbose_name='Ключевые слова')),
                ('news_title', models.CharField(max_length=255, verbose_name='Заголовок новости')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path, verbose_name='Изображение на странице предпросмотра')),
                ('published', models.DateField(null=True, verbose_name='Дата публикации')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('keywords', models.TextField(blank=True, verbose_name='Ключевые слова')),
                ('page_title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('other_news_title', models.CharField(max_length=255, verbose_name='Заголовок "Другие новости"')),
            ],
            options={
                'verbose_name': 'Общая страница новостей',
                'verbose_name_plural': 'Общая страница новостей',
            },
        ),
        migrations.CreateModel(
            name='NewsSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path, verbose_name='Изображение')),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_images', to='news.newsitem', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение новости',
                'verbose_name_plural': 'Изображения новости',
            },
        ),
    ]
