# Generated by Django 3.2.8 on 2024-06-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_newsitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание SEO'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='keywords',
            field=models.TextField(blank=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Заголовок SEO'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание SEO'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='keywords',
            field=models.TextField(blank=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Заголовок SEO'),
        ),
    ]
