# Generated by Django 3.2.8 on 2024-06-27 08:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20240615_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='keywords_en',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='keywords_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='keywords_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='news_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок новости'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='news_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок новости'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='news_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок новости'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='text_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок SEO'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок SEO'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок SEO'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='keywords_en',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='keywords_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='keywords_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='other_news_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Другие новости"'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='other_news_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Другие новости"'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='other_news_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Другие новости"'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='page_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='page_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='page_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='title_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок SEO'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='title_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок SEO'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='title_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок SEO'),
        ),
    ]
