# Generated by Django 3.2.8 on 2024-06-27 16:08

from django.db import migrations, models
import toyboss.functions


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20240627_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsslider',
            name='image_1499_jpg',
            field=models.ImageField(upload_to=toyboss.functions.get_file_path),
        ),
        migrations.AlterField(
            model_name='newsslider',
            name='image_1499_webp',
            field=models.ImageField(upload_to=toyboss.functions.get_file_path),
        ),
    ]
