# Generated by Django 3.2.8 on 2024-07-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20240627_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='button_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Наименование кнопки'),
            preserve_default=False,
        ),
    ]
