# Generated by Django 3.2.8 on 2024-07-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newspage_button_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='button_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование кнопки'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='button_name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование кнопки'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='button_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование кнопки'),
        ),
    ]
