# Generated by Django 3.2.8 on 2024-09-23 12:14

from django.db import migrations, models
import toyboss.functions


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20240703_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsslider',
            name='image_main_jpg',
            field=models.ImageField(default=1, upload_to=toyboss.functions.get_file_path),
            preserve_default=False,
        ),
    ]
