# Generated by Django 3.2.8 on 2024-08-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=255, verbose_name='О нас')),
                ('about_ru', models.CharField(max_length=255, null=True, verbose_name='О нас')),
                ('about_ky', models.CharField(max_length=255, null=True, verbose_name='О нас')),
                ('about_en', models.CharField(max_length=255, null=True, verbose_name='О нас')),
                ('production', models.CharField(max_length=255, verbose_name='Производство')),
                ('production_ru', models.CharField(max_length=255, null=True, verbose_name='Производство')),
                ('production_ky', models.CharField(max_length=255, null=True, verbose_name='Производство')),
                ('production_en', models.CharField(max_length=255, null=True, verbose_name='Производство')),
                ('product', models.CharField(max_length=255, verbose_name='Продукция')),
                ('product_ru', models.CharField(max_length=255, null=True, verbose_name='Продукция')),
                ('product_ky', models.CharField(max_length=255, null=True, verbose_name='Продукция')),
                ('product_en', models.CharField(max_length=255, null=True, verbose_name='Продукция')),
                ('cooperation', models.CharField(max_length=255, verbose_name='Сотрудничество')),
                ('cooperation_ru', models.CharField(max_length=255, null=True, verbose_name='Сотрудничество')),
                ('cooperation_ky', models.CharField(max_length=255, null=True, verbose_name='Сотрудничество')),
                ('cooperation_en', models.CharField(max_length=255, null=True, verbose_name='Сотрудничество')),
                ('news', models.CharField(max_length=255, verbose_name='Новости')),
                ('news_ru', models.CharField(max_length=255, null=True, verbose_name='Новости')),
                ('news_ky', models.CharField(max_length=255, null=True, verbose_name='Новости')),
                ('news_en', models.CharField(max_length=255, null=True, verbose_name='Новости')),
                ('contact', models.CharField(max_length=255, verbose_name='Контакты')),
                ('contact_ru', models.CharField(max_length=255, null=True, verbose_name='Контакты')),
                ('contact_ky', models.CharField(max_length=255, null=True, verbose_name='Контакты')),
                ('contact_en', models.CharField(max_length=255, null=True, verbose_name='Контакты')),
                ('ustukan_game_general', models.CharField(max_length=255, verbose_name='Игра Устукан')),
                ('ustukan_game_general_ru', models.CharField(max_length=255, null=True, verbose_name='Игра Устукан')),
                ('ustukan_game_general_ky', models.CharField(max_length=255, null=True, verbose_name='Игра Устукан')),
                ('ustukan_game_general_en', models.CharField(max_length=255, null=True, verbose_name='Игра Устукан')),
                ('ustukan_game_first', models.CharField(blank=True, max_length=255, verbose_name='Игра Устукан (все еще в разработке) (первое предложение)')),
                ('ustukan_game_first_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Игра Устукан (все еще в разработке) (первое предложение)')),
                ('ustukan_game_first_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Игра Устукан (все еще в разработке) (первое предложение)')),
                ('ustukan_game_first_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Игра Устукан (все еще в разработке) (первое предложение)')),
                ('ustukan_game_second', models.CharField(blank=True, max_length=255, verbose_name='Игра Устукан (все еще в разработке) (второе предложение)')),
            ],
            options={
                'verbose_name': 'Панель навигации',
                'verbose_name_plural': 'Панель навигации',
            },
        ),
    ]
