# Generated by Django 3.2.8 on 2024-08-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationmenu',
            name='ustukan_game_second_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Игра Устукан (все еще в разработке) (второе предложение)'),
        ),
        migrations.AddField(
            model_name='navigationmenu',
            name='ustukan_game_second_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Игра Устукан (все еще в разработке) (второе предложение)'),
        ),
        migrations.AddField(
            model_name='navigationmenu',
            name='ustukan_game_second_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Игра Устукан (все еще в разработке) (второе предложение)'),
        ),
    ]
