# Generated by Django 3.2.8 on 2024-08-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_auto_20240808_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок под логотипом')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок под логотипом')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок под логотипом')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок под логотипом')),
                ('rights', models.CharField(max_length=255, verbose_name='Заголовок (все права защищены)')),
                ('rights_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок (все права защищены)')),
                ('rights_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок (все права защищены)')),
                ('rights_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок (все права защищены)')),
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футер',
            },
        ),
    ]
