# Generated by Django 3.2.8 on 2024-08-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='whatsup_number',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер Whatsapp'),
            preserve_default=False,
        ),
    ]
