# Generated by Django 3.2.8 on 2024-08-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_footer_whatsup_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок (Адрес)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='office_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок (Офис в г. Бишкек)'),
            preserve_default=False,
        ),
    ]
