# Generated by Django 3.2.8 on 2024-08-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0006_footer_phone_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='phone_number',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
