# Generated by Django 3.2.8 on 2024-08-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0007_footer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
