# Generated by Django 3.2.8 on 2024-08-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0008_footer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок (Адрес)'),
        ),
        migrations.AddField(
            model_name='footer',
            name='address_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок (Адрес)'),
        ),
        migrations.AddField(
            model_name='footer',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок (Адрес)'),
        ),
        migrations.AddField(
            model_name='footer',
            name='office_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок (Офис в г. Бишкек)'),
        ),
        migrations.AddField(
            model_name='footer',
            name='office_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок (Офис в г. Бишкек)'),
        ),
        migrations.AddField(
            model_name='footer',
            name='office_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок (Офис в г. Бишкек)'),
        ),
        migrations.AddField(
            model_name='footer',
            name='phone_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок (телефон)'),
        ),
        migrations.AddField(
            model_name='footer',
            name='phone_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок (телефон)'),
        ),
        migrations.AddField(
            model_name='footer',
            name='phone_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок (телефон)'),
        ),
    ]
