# Generated by Django 3.2.8 on 2024-08-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0009_auto_20240809_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationmenu',
            name='faq',
            field=models.CharField(default=1, max_length=255, verbose_name='FAQ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navigationmenu',
            name='faq_en',
            field=models.CharField(max_length=255, null=True, verbose_name='FAQ'),
        ),
        migrations.AddField(
            model_name='navigationmenu',
            name='faq_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='FAQ'),
        ),
        migrations.AddField(
            model_name='navigationmenu',
            name='faq_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='FAQ'),
        ),
    ]
