# Generated by Django 3.2.8 on 2024-09-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0010_auto_20240809_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_not_found_first', models.CharField(max_length=255, verbose_name='Страница не найдена')),
                ('page_not_found_first_ru', models.CharField(max_length=255, null=True, verbose_name='Страница не найдена')),
                ('page_not_found_first_ky', models.CharField(max_length=255, null=True, verbose_name='Страница не найдена')),
                ('page_not_found_first_en', models.CharField(max_length=255, null=True, verbose_name='Страница не найдена')),
                ('page_not_found_second', models.CharField(max_length=255, verbose_name='Страница, на которую вы пытаетесь попасть, не существует или была удалена')),
                ('page_not_found_second_ru', models.CharField(max_length=255, null=True, verbose_name='Страница, на которую вы пытаетесь попасть, не существует или была удалена')),
                ('page_not_found_second_ky', models.CharField(max_length=255, null=True, verbose_name='Страница, на которую вы пытаетесь попасть, не существует или была удалена')),
                ('page_not_found_second_en', models.CharField(max_length=255, null=True, verbose_name='Страница, на которую вы пытаетесь попасть, не существует или была удалена')),
                ('to_main', models.CharField(max_length=255, verbose_name='На главную')),
                ('to_main_ru', models.CharField(max_length=255, null=True, verbose_name='На главную')),
                ('to_main_ky', models.CharField(max_length=255, null=True, verbose_name='На главную')),
                ('to_main_en', models.CharField(max_length=255, null=True, verbose_name='На главную')),
            ],
            options={
                'verbose_name': '404',
                'verbose_name_plural': '404',
            },
        ),
    ]
