# Generated by Django 3.2.8 on 2024-09-23 08:50

from django.db import migrations, models
import toyboss.functions


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0011_notfound'),
    ]

    operations = [
        migrations.AddField(
            model_name='notfound',
            name='image',
            field=models.ImageField(default=1, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path, verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
