# Generated by Django 3.2.8 on 2024-09-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0012_notfound_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTranslations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_button', models.CharField(max_length=255, verbose_name='Подробнее')),
                ('detail_button_ru', models.CharField(max_length=255, null=True, verbose_name='Подробнее')),
                ('detail_button_ky', models.CharField(max_length=255, null=True, verbose_name='Подробнее')),
                ('detail_button_en', models.CharField(max_length=255, null=True, verbose_name='Подробнее')),
            ],
            options={
                'verbose_name': 'Общие переводы',
                'verbose_name_plural': 'Общие переводы',
            },
        ),
    ]
