# Generated by Django 3.2.8 on 2024-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0013_generaltranslations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaltranslations',
            name='detail_button',
            field=models.CharField(max_length=255, verbose_name='Кнопка "Подробнее"'),
        ),
        migrations.AlterField(
            model_name='generaltranslations',
            name='detail_button_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Кнопка "Подробнее"'),
        ),
        migrations.AlterField(
            model_name='generaltranslations',
            name='detail_button_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Кнопка "Подробнее"'),
        ),
        migrations.AlterField(
            model_name='generaltranslations',
            name='detail_button_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Кнопка "Подробнее"'),
        ),
    ]
