# Generated by Django 3.2.8 on 2024-09-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0014_auto_20240923_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaltranslations',
            name='product_all',
            field=models.CharField(default=1, max_length=255, verbose_name='Состав (продукты, главная страница)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generaltranslations',
            name='product_all_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Состав (продукты, главная страница)'),
        ),
        migrations.AddField(
            model_name='generaltranslations',
            name='product_all_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Состав (продукты, главная страница)'),
        ),
        migrations.AddField(
            model_name='generaltranslations',
            name='product_all_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Состав (продукты, главная страница)'),
        ),
        migrations.AddField(
            model_name='generaltranslations',
            name='product_compound',
            field=models.CharField(default=1, max_length=255, verbose_name='Состав (продукты)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generaltranslations',
            name='product_compound_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Состав (продукты)'),
        ),
        migrations.AddField(
            model_name='generaltranslations',
            name='product_compound_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Состав (продукты)'),
        ),
        migrations.AddField(
            model_name='generaltranslations',
            name='product_compound_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Состав (продукты)'),
        ),
        migrations.AddField(
            model_name='generaltranslations',
            name='product_description',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание (продукты)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generaltranslations',
            name='product_description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание (продукты)'),
        ),
        migrations.AddField(
            model_name='generaltranslations',
            name='product_description_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание (продукты)'),
        ),
        migrations.AddField(
            model_name='generaltranslations',
            name='product_description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание (продукты)'),
        ),
    ]
