# Generated by Django 3.2.8 on 2024-09-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0015_auto_20240923_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaltranslations',
            name='product_all',
            field=models.CharField(max_length=255, verbose_name='Все (продукты, главная страница)'),
        ),
        migrations.AlterField(
            model_name='generaltranslations',
            name='product_all_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Все (продукты, главная страница)'),
        ),
        migrations.AlterField(
            model_name='generaltranslations',
            name='product_all_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Все (продукты, главная страница)'),
        ),
        migrations.AlterField(
            model_name='generaltranslations',
            name='product_all_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Все (продукты, главная страница)'),
        ),
    ]
