# Generated by Django 3.2.8 on 2024-06-16 15:03

from django.db import migrations, models
import toyboss.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('category_title', models.CharField(max_length=255, verbose_name='Наименование категории')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория продукта',
                'verbose_name_plural': 'Категории продуктов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок SEO')),
                ('description', models.TextField(blank=True, verbose_name='Описание SEO')),
                ('keywords', models.TextField(blank=True, verbose_name='Ключевые слова SEO')),
                ('page_title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
            ],
            options={
                'verbose_name': 'Общая страница продуктов',
                'verbose_name_plural': 'Общая страница продуктов',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('product_title', models.CharField(max_length=255, verbose_name='Наименование продукта')),
                ('prev_description', models.TextField(verbose_name='Описание на предпросмотре')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('compound', models.TextField(blank=True, verbose_name='Состав')),
                ('spices', models.TextField(blank=True, verbose_name='Специи')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path, verbose_name='Изображение')),
                ('main_show', models.BooleanField(blank=True, default=False, verbose_name='Отобразить на главной странице')),
                ('hit_show', models.BooleanField(blank=True, default=False, verbose_name='Хит продаж')),
                ('count_sum', models.CharField(max_length=255, verbose_name='Количество любителей')),
                ('count_subtitle', models.CharField(help_text='Например - "любителей пепперони"', max_length=255, verbose_name='Подзаголовок количества любителей')),
                ('first_fact', models.TextField(blank=True, verbose_name='Интересный факт о продукте, #1')),
                ('second_fact', models.TextField(blank=True, verbose_name='Интересный факт о продукте, #2')),
                ('third_fact', models.TextField(blank=True, verbose_name='Интересный факт о продукте, #3')),
                ('recipe', models.URLField(blank=True, verbose_name='Посмотреть рецепт')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['order'],
            },
        ),
    ]
