# Generated by Django 3.2.8 on 2024-06-27 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='product.productcategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
