# Generated by Django 3.2.8 on 2024-06-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='count_subtitle',
            field=models.CharField(blank=True, help_text='Например - "любителей пепперони"', max_length=255, verbose_name='Подзаголовок количества любителей'),
        ),
        migrations.AlterField(
            model_name='products',
            name='count_sum',
            field=models.CharField(blank=True, max_length=255, verbose_name='Количество любителей'),
        ),
    ]
