# Generated by Django 3.2.8 on 2024-07-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20240628_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='count_subtitle',
        ),
        migrations.RemoveField(
            model_name='products',
            name='count_sum',
        ),
        migrations.RemoveField(
            model_name='products',
            name='first_fact',
        ),
        migrations.RemoveField(
            model_name='products',
            name='hit_show',
        ),
        migrations.RemoveField(
            model_name='products',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='products',
            name='second_fact',
        ),
        migrations.RemoveField(
            model_name='products',
            name='spices',
        ),
        migrations.RemoveField(
            model_name='products',
            name='third_fact',
        ),
    ]
