# Generated by Django 3.2.8 on 2024-07-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_products_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='chicken_mark',
            field=models.BooleanField(blank=True, default=False, verbose_name='Галочка для куриного мяса'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='sandwich_mark',
            field=models.BooleanField(blank=True, default=False, verbose_name='Галочка для категории сэндвичей'),
        ),
    ]
