# Generated by Django 3.2.8 on 2024-07-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20240716_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='prev_description',
        ),
        migrations.AddField(
            model_name='products',
            name='product_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование продукта'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование продукта'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование продукта'),
        ),
    ]
