# Generated by Django 3.2.8 on 2024-07-17 07:07

from django.db import migrations, models
import toyboss.functions


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20240717_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_detail',
            field=models.ImageField(blank=True, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path),
        ),
    ]
