# Generated by Django 3.2.8 on 2024-08-06 15:43

from django.db import migrations, models
import toyboss.functions


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_products_image_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='image_boiled',
            field=models.ImageField(blank=True, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path, verbose_name='Изображение 274 x 331 (вареная колбаса)'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_chicken',
            field=models.ImageField(blank=True, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path, verbose_name='Изображение 185 x 267 (куриное мясо)'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_sausages',
            field=models.ImageField(blank=True, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path, verbose_name='Изображение 199 x 251 (куриное мясо)'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_semismocked',
            field=models.ImageField(blank=True, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path, verbose_name='Изображение 239 x 306 (полукопченая колбаса)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_detail',
            field=models.ImageField(blank=True, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path, verbose_name='Детальное изображение продукции'),
        ),
    ]
