# Generated by Django 3.2.8 on 2024-08-08 14:11

from django.db import migrations, models
import toyboss.functions


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20240806_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_sausages',
            field=models.ImageField(blank=True, help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path, verbose_name='Изображение 199 x 251 (сосиски)'),
        ),
    ]
