# Generated by Django 3.2.8 on 2024-08-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_products_image_sausages'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='keywords_en',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='keywords_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='keywords_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='page_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='page_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='page_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='title_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок SEO'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='title_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок SEO'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='title_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок SEO'),
        ),
    ]
