# Generated by Django 3.2.8 on 2024-08-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_products_catalog_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='catalog_show',
            field=models.BooleanField(blank=True, default=True, verbose_name='Отобразить на странице продукции (каталога)'),
        ),
    ]
