# Generated by Django 3.2.8 on 2024-08-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_products_catalog_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='catalog_show',
        ),
    ]
