# Generated by Django 3.2.8 on 2024-06-15 15:14

from django.db import migrations, models
import toyboss.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CooperationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок SEO')),
                ('description', models.TextField(blank=True, verbose_name='Описание SEO')),
                ('keywords', models.TextField(blank=True, verbose_name='Ключевые слова SEO')),
                ('page_title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path, verbose_name='Баннер')),
                ('left_text', models.TextField(verbose_name='Текст слева')),
                ('right_text', models.TextField(verbose_name='Текст справа')),
            ],
            options={
                'verbose_name': 'Сотрудничество',
                'verbose_name_plural': 'Сотрудничество',
            },
        ),
        migrations.CreateModel(
            name='Retailsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Розничные продажи')),
                ('subtitle', models.TextField(verbose_name='Подзаголовок')),
                ('first_phone', models.CharField(max_length=255, verbose_name='Телефон (Бишкек)')),
                ('second_phone', models.CharField(max_length=255, verbose_name='Телефон (Ош)')),
            ],
            options={
                'verbose_name': 'Розничные продажи',
                'verbose_name_plural': 'Розничные продажи',
            },
        ),
        migrations.CreateModel(
            name='Wholesale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Оптовые продажи')),
                ('subtitle', models.TextField(verbose_name='Подзаголовок')),
                ('first_phone', models.CharField(max_length=255, verbose_name='Телефон (Бишкек)')),
                ('second_phone', models.CharField(max_length=255, verbose_name='Телефон (Ош)')),
            ],
            options={
                'verbose_name': 'Оптовые продажи',
                'verbose_name_plural': 'Оптовые продажи',
            },
        ),
    ]
