# Generated by Django 3.2.8 on 2024-06-15 15:20

from django.db import migrations, models
import django.db.models.deletion
import toyboss.functions


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Партнеры')),
                ('subtitle', models.TextField(verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Партнеры',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='PartnersItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path, verbose_name='Логотип')),
                ('partners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_items', to='cooperation.partners')),
            ],
            options={
                'verbose_name': 'Изображение партнера',
                'verbose_name_plural': 'Изображения партнеров',
            },
        ),
    ]
