# Generated by Django 3.2.8 on 2024-07-02 05:46

from django.db import migrations, models
import toyboss.functions


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0002_partners_partnersitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperationpage',
            name='image_1500_jpg',
            field=models.ImageField(blank=True, upload_to=toyboss.functions.get_file_path),
        ),
        migrations.AddField(
            model_name='cooperationpage',
            name='image_1500_webp',
            field=models.ImageField(blank=True, upload_to=toyboss.functions.get_file_path),
        ),
    ]
