# Generated by Django 3.2.8 on 2024-07-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0004_auto_20240702_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperationpage',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='cooperationpage',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='cooperationpage',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='cooperationpage',
            name='keywords_en',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AddField(
            model_name='cooperationpage',
            name='keywords_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AddField(
            model_name='cooperationpage',
            name='keywords_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AddField(
            model_name='cooperationpage',
            name='left_text_en',
            field=models.TextField(null=True, verbose_name='Текст слева'),
        ),
        migrations.AddField(
            model_name='cooperationpage',
            name='left_text_ky',
            field=models.TextField(null=True, verbose_name='Текст слева'),
        ),
        migrations.AddField(
            model_name='cooperationpage',
            name='left_text_ru',
            field=models.TextField(null=True, verbose_name='Текст слева'),
        ),
        migrations.AddField(
            model_name='cooperationpage',
            name='page_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='cooperationpage',
            name='page_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='cooperationpage',
            name='page_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='cooperationpage',
            name='right_text_en',
            field=models.TextField(null=True, verbose_name='Текст справа'),
        ),
        migrations.AddField(
            model_name='cooperationpage',
            name='right_text_ky',
            field=models.TextField(null=True, verbose_name='Текст справа'),
        ),
        migrations.AddField(
            model_name='cooperationpage',
            name='right_text_ru',
            field=models.TextField(null=True, verbose_name='Текст справа'),
        ),
        migrations.AddField(
            model_name='cooperationpage',
            name='title_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок SEO'),
        ),
        migrations.AddField(
            model_name='cooperationpage',
            name='title_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок SEO'),
        ),
        migrations.AddField(
            model_name='cooperationpage',
            name='title_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок SEO'),
        ),
    ]
