# Generated by Django 3.2.8 on 2024-07-02 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0005_auto_20240702_0555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperationpage',
            options={'verbose_name': 'Общая страница сотрудничества', 'verbose_name_plural': 'Общая страница сотрудничества'},
        ),
    ]
