# Generated by Django 3.2.8 on 2024-07-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0008_auto_20240702_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsale',
            name='first_city',
            field=models.CharField(default=1, max_length=255, verbose_name='Указание города (Бишкек)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retailsale',
            name='second_city',
            field=models.CharField(default=1, max_length=255, verbose_name='Указание города (Ош)'),
            preserve_default=False,
        ),
    ]
