# Generated by Django 3.2.8 on 2024-07-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0009_auto_20240702_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsale',
            name='first_city_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Указание города (Бишкек)'),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='first_city_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Указание города (Бишкек)'),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='first_city_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Указание города (Бишкек)'),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='second_city_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Указание города (Ош)'),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='second_city_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Указание города (Ош)'),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='second_city_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Указание города (Ош)'),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='subtitle_en',
            field=models.TextField(null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='subtitle_ky',
            field=models.TextField(null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='subtitle_ru',
            field=models.TextField(null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Розничные продажи'),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Розничные продажи'),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Розничные продажи'),
        ),
    ]
