# Generated by Django 3.2.8 on 2024-07-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0010_auto_20240702_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='subtitle_en',
            field=models.TextField(null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='partners',
            name='subtitle_ky',
            field=models.TextField(null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='partners',
            name='subtitle_ru',
            field=models.TextField(null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='partners',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Партнеры'),
        ),
        migrations.AddField(
            model_name='partners',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Партнеры'),
        ),
        migrations.AddField(
            model_name='partners',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Партнеры'),
        ),
    ]
