# Generated by Django 3.2.8 on 2024-07-04 17:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0011_auto_20240702_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255, verbose_name='Работа в Тойбосс')),
                ('subtitle', models.TextField(verbose_name='Подзаголовок (Хотите расти вместе с нами...)')),
                ('name', models.CharField(max_length=255, verbose_name='Ваше имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Ваш номер')),
                ('position', models.CharField(max_length=255, verbose_name='Желаемая позиция')),
                ('message', models.CharField(max_length=255, verbose_name='Ваше сообщение')),
                ('rules', ckeditor.fields.RichTextField(blank=True, verbose_name='Условия соглашения')),
                ('file', models.CharField(max_length=255, verbose_name='Прикрепить файл')),
                ('send_button', models.CharField(max_length=255, verbose_name='Кнопка "Отправить"')),
            ],
            options={
                'verbose_name': 'Форма (Сотрудничество)',
                'verbose_name_plural': 'Форма (Сотрудничество)',
            },
        ),
    ]
