# Generated by Django 3.2.8 on 2024-07-04 17:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0012_cooperationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperationform',
            name='file_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Прикрепить файл'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='file_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Прикрепить файл'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='file_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Прикрепить файл'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='main_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Работа в Тойбосс'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='main_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Работа в Тойбосс'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='main_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Работа в Тойбосс'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='message_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Ваше сообщение'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='message_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Ваше сообщение'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='message_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ваше сообщение'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Ваше имя'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Ваше имя'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ваше имя'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='phone_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Ваш номер'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='phone_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Ваш номер'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='phone_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ваш номер'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Желаемая позиция'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='position_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Желаемая позиция'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Желаемая позиция'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='rules_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Условия соглашения'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='rules_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Условия соглашения'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='rules_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Условия соглашения'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='send_button_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Кнопка "Отправить"'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='send_button_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Кнопка "Отправить"'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='send_button_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Кнопка "Отправить"'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='subtitle_en',
            field=models.TextField(null=True, verbose_name='Подзаголовок (Хотите расти вместе с нами...)'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='subtitle_ky',
            field=models.TextField(null=True, verbose_name='Подзаголовок (Хотите расти вместе с нами...)'),
        ),
        migrations.AddField(
            model_name='cooperationform',
            name='subtitle_ru',
            field=models.TextField(null=True, verbose_name='Подзаголовок (Хотите расти вместе с нами...)'),
        ),
    ]
