# Generated by Django 3.2.8 on 2024-07-05 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0013_auto_20240704_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailsale',
            options={'verbose_name': 'Сотрудничество и предложения', 'verbose_name_plural': 'Сотрудничество и предложения'},
        ),
    ]
