# Generated by Django 3.2.8 on 2024-10-07 05:53

from django.db import migrations, models
import toyboss.functions


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0014_alter_retailsale_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersitems',
            name='image_1500_png',
            field=models.ImageField(default=1, upload_to=toyboss.functions.get_file_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnersitems',
            name='image_1500_webp',
            field=models.ImageField(default=1, upload_to=toyboss.functions.get_file_path),
            preserve_default=False,
        ),
    ]
