# Generated by Django 3.2.8 on 2024-06-16 15:25

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import toyboss.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('first_advantage', models.CharField(max_length=255, verbose_name='Первое преимущество')),
                ('second_advantage', models.CharField(max_length=255, verbose_name='Второе преимущество')),
                ('third_advantage', models.CharField(max_length=255, verbose_name='Третье преимущество')),
                ('fourth_advantage', models.CharField(max_length=255, verbose_name='Четвертое преимущество')),
                ('fifth_advantage', models.CharField(max_length=255, verbose_name='Пятое преимущество')),
                ('sixth_advantage', models.CharField(max_length=255, verbose_name='Шестое преимущество')),
            ],
            options={
                'verbose_name': 'Преимущества',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('point_title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('icon', models.FileField(help_text='Формат файла: SVG. Ограничение размера: 1 Мбайт.', upload_to=toyboss.functions.get_file_path, validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Иконка')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Преимущества',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок SEO')),
                ('description', models.TextField(blank=True, verbose_name='Описание SEO')),
                ('keywords', models.TextField(blank=True, verbose_name='Ключевые слова SEO')),
                ('page_title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('youtube_link', models.URLField(verbose_name='Ссылка на Youtube')),
            ],
            options={
                'verbose_name': 'Общая страница производства',
                'verbose_name_plural': 'Общая страница производства',
            },
        ),
        migrations.CreateModel(
            name='PointsSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path, verbose_name='Изображение')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_slider', to='production.points', verbose_name='Пункт')),
            ],
            options={
                'verbose_name': 'Изображение в слайдере',
                'verbose_name_plural': 'Изображения в слайдере',
            },
        ),
    ]
