# Generated by Django 3.2.8 on 2024-06-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={'ordering': ['id'], 'verbose_name': 'Пункт', 'verbose_name_plural': 'Пункты'},
        ),
    ]
