# Generated by Django 3.2.8 on 2024-11-17 14:49

from django.db import migrations, models
import toyboss.functions


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_auto_20240627_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsslider',
            name='image_1470_jpg',
            field=models.ImageField(default=1, upload_to=toyboss.functions.get_file_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointsslider',
            name='image_1470_webp',
            field=models.ImageField(default=1, upload_to=toyboss.functions.get_file_path),
            preserve_default=False,
        ),
    ]
