# Generated by Django 3.2.8 on 2024-07-02 12:45

from django.db import migrations, models
import django.db.models.deletion
import toyboss.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sandwich_text', models.TextField(verbose_name='Текст сэндвичей')),
                ('toyboss_text', models.TextField(verbose_name='Текст колбасы')),
                ('agrokush_text', models.TextField(verbose_name='Текст Агрокуша')),
                ('broiler_text', models.TextField(verbose_name='Текст Кыргыз Бройлера')),
            ],
            options={
                'verbose_name': 'Группа компаний',
                'verbose_name_plural': 'Группа компаний',
            },
        ),
        migrations.CreateModel(
            name='MainCooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.TextField(verbose_name='Подзаголовок')),
                ('first_city', models.CharField(max_length=255, verbose_name='Указание города (Бишкек)')),
                ('second_city', models.CharField(max_length=255, verbose_name='Указание города (Ош)')),
                ('first_phone', models.CharField(max_length=255, verbose_name='Телефон (Бишкек)')),
                ('second_phone', models.CharField(max_length=255, verbose_name='Телефон (Ош)')),
            ],
            options={
                'verbose_name': 'Сотрудничество',
                'verbose_name_plural': 'Сотрудничество',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок SEO')),
                ('description', models.TextField(blank=True, verbose_name='Описание SEO')),
                ('keywords', models.TextField(blank=True, verbose_name='Ключевые слова SEO')),
            ],
            options={
                'verbose_name': 'Общая страница',
                'verbose_name_plural': 'Общая страница',
            },
        ),
        migrations.CreateModel(
            name='MainProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('top_text', models.TextField(verbose_name='Текст сверху')),
                ('bottom_text', models.TextField(verbose_name='Текст снизу')),
            ],
            options={
                'verbose_name': 'Производство',
                'verbose_name_plural': 'Производство',
            },
        ),
        migrations.CreateModel(
            name='MainProdSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path, verbose_name='Изображение')),
                ('main_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_prod_slider', to='main.mainpage')),
            ],
            options={
                'verbose_name': 'Слайдер производства',
                'verbose_name_plural': 'Слайдер производства',
            },
        ),
        migrations.CreateModel(
            name='MainPageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path, verbose_name='Изображение')),
                ('main_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_page_slider', to='main.mainpage')),
            ],
            options={
                'verbose_name': 'Главный слайдер',
                'verbose_name_plural': 'Главный слайдер',
            },
        ),
    ]
