# Generated by Django 3.2.8 on 2024-07-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_survey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опрос'},
        ),
    ]
