# Generated by Django 3.2.8 on 2024-07-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_survey_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincooperation',
            name='first_city_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Указание города (Бишкек)'),
        ),
        migrations.AddField(
            model_name='maincooperation',
            name='first_city_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Указание города (Бишкек)'),
        ),
        migrations.AddField(
            model_name='maincooperation',
            name='first_city_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Указание города (Бишкек)'),
        ),
        migrations.AddField(
            model_name='maincooperation',
            name='second_city_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Указание города (Ош)'),
        ),
        migrations.AddField(
            model_name='maincooperation',
            name='second_city_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Указание города (Ош)'),
        ),
        migrations.AddField(
            model_name='maincooperation',
            name='second_city_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Указание города (Ош)'),
        ),
        migrations.AddField(
            model_name='maincooperation',
            name='subtitle_en',
            field=models.TextField(null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='maincooperation',
            name='subtitle_ky',
            field=models.TextField(null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='maincooperation',
            name='subtitle_ru',
            field=models.TextField(null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='maincooperation',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='maincooperation',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='maincooperation',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
