# Generated by Django 3.2.8 on 2024-07-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20240703_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='agrokush_text_en',
            field=models.TextField(null=True, verbose_name='Текст Агрокуша'),
        ),
        migrations.AddField(
            model_name='groups',
            name='agrokush_text_ky',
            field=models.TextField(null=True, verbose_name='Текст Агрокуша'),
        ),
        migrations.AddField(
            model_name='groups',
            name='agrokush_text_ru',
            field=models.TextField(null=True, verbose_name='Текст Агрокуша'),
        ),
        migrations.AddField(
            model_name='groups',
            name='broiler_text_en',
            field=models.TextField(null=True, verbose_name='Текст Кыргыз Бройлера'),
        ),
        migrations.AddField(
            model_name='groups',
            name='broiler_text_ky',
            field=models.TextField(null=True, verbose_name='Текст Кыргыз Бройлера'),
        ),
        migrations.AddField(
            model_name='groups',
            name='broiler_text_ru',
            field=models.TextField(null=True, verbose_name='Текст Кыргыз Бройлера'),
        ),
        migrations.AddField(
            model_name='groups',
            name='sandwich_text_en',
            field=models.TextField(null=True, verbose_name='Текст сэндвичей'),
        ),
        migrations.AddField(
            model_name='groups',
            name='sandwich_text_ky',
            field=models.TextField(null=True, verbose_name='Текст сэндвичей'),
        ),
        migrations.AddField(
            model_name='groups',
            name='sandwich_text_ru',
            field=models.TextField(null=True, verbose_name='Текст сэндвичей'),
        ),
        migrations.AddField(
            model_name='groups',
            name='toyboss_text_en',
            field=models.TextField(null=True, verbose_name='Текст колбасы'),
        ),
        migrations.AddField(
            model_name='groups',
            name='toyboss_text_ky',
            field=models.TextField(null=True, verbose_name='Текст колбасы'),
        ),
        migrations.AddField(
            model_name='groups',
            name='toyboss_text_ru',
            field=models.TextField(null=True, verbose_name='Текст колбасы'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='keywords_en',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='keywords_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='keywords_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова SEO'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='title_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок SEO'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='title_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок SEO'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='title_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок SEO'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='subtitle_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='mainprod',
            name='bottom_text_en',
            field=models.TextField(null=True, verbose_name='Текст снизу'),
        ),
        migrations.AddField(
            model_name='mainprod',
            name='bottom_text_ky',
            field=models.TextField(null=True, verbose_name='Текст снизу'),
        ),
        migrations.AddField(
            model_name='mainprod',
            name='bottom_text_ru',
            field=models.TextField(null=True, verbose_name='Текст снизу'),
        ),
        migrations.AddField(
            model_name='mainprod',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='mainprod',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='mainprod',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='mainprod',
            name='top_text_en',
            field=models.TextField(null=True, verbose_name='Текст сверху'),
        ),
        migrations.AddField(
            model_name='mainprod',
            name='top_text_ky',
            field=models.TextField(null=True, verbose_name='Текст сверху'),
        ),
        migrations.AddField(
            model_name='mainprod',
            name='top_text_ru',
            field=models.TextField(null=True, verbose_name='Текст сверху'),
        ),
        migrations.AddField(
            model_name='survey',
            name='button_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование кнопки'),
        ),
        migrations.AddField(
            model_name='survey',
            name='button_name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование кнопки'),
        ),
        migrations.AddField(
            model_name='survey',
            name='button_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование кнопки'),
        ),
        migrations.AddField(
            model_name='survey',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='survey',
            name='subtitle_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='survey',
            name='subtitle_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='survey',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='survey',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='survey',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
    ]
