# Generated by Django 3.2.8 on 2024-07-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20240705_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
