# Generated by Django 3.2.8 on 2024-07-05 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20240705_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainprodslider',
            name='main_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_prod_slider', to='main.mainprod'),
        ),
    ]
