# Generated by Django 3.2.8 on 2024-07-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20240717_0410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpageslider',
            options={'verbose_name': 'Главный слайдер', 'verbose_name_plural': 'Главный слайдер'},
        ),
        migrations.RemoveField(
            model_name='mainpageslider',
            name='order',
        ),
    ]
