# Generated by Django 3.2.8 on 2024-07-17 04:18

from django.db import migrations, models
import toyboss.functions


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_mainpageslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Главный слайдер',
                'verbose_name_plural': 'Главный слайдер',
                'ordering': ['order'],
            },
        ),
    ]
