# Generated by Django 3.2.8 on 2024-07-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_mainpageslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageslider',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='subtitle_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
