# Generated by Django 3.2.8 on 2024-07-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20240717_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line', models.CharField(max_length=255, verbose_name='Первая строка')),
                ('first_line_ru', models.CharField(max_length=255, null=True, verbose_name='Первая строка')),
                ('first_line_ky', models.CharField(max_length=255, null=True, verbose_name='Первая строка')),
                ('first_line_en', models.CharField(max_length=255, null=True, verbose_name='Первая строка')),
                ('second_line', models.CharField(max_length=255, verbose_name='Вторая строка')),
                ('second_line_ru', models.CharField(max_length=255, null=True, verbose_name='Вторая строка')),
                ('second_line_ky', models.CharField(max_length=255, null=True, verbose_name='Вторая строка')),
                ('second_line_en', models.CharField(max_length=255, null=True, verbose_name='Вторая строка')),
                ('third_line', models.CharField(max_length=255, verbose_name='Вторая строка')),
                ('third_line_ru', models.CharField(max_length=255, null=True, verbose_name='Вторая строка')),
                ('third_line_ky', models.CharField(max_length=255, null=True, verbose_name='Вторая строка')),
                ('third_line_en', models.CharField(max_length=255, null=True, verbose_name='Вторая строка')),
                ('first_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('first_name_ru', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('first_name_ky', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('first_name_en', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('position_ru', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('position_ky', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(max_length=255, null=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Цитата гендира на главной странице',
                'verbose_name_plural': 'Цитата гендира на главной странице',
            },
        ),
    ]
