# Generated by Django 3.2.8 on 2024-10-22 13:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20240809_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainquote',
            name='mission_text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст миссии'),
        ),
        migrations.AlterField(
            model_name='mainquote',
            name='mission_text_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст миссии'),
        ),
        migrations.AlterField(
            model_name='mainquote',
            name='mission_text_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст миссии'),
        ),
        migrations.AlterField(
            model_name='mainquote',
            name='mission_text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст миссии'),
        ),
    ]
