# Generated by Django 3.2.8 on 2024-10-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20241022_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainquote',
            options={'verbose_name': 'История, миссия и ценности', 'verbose_name_plural': 'История, миссия и ценности'},
        ),
    ]
