# Generated by Django 3.2.8 on 2024-06-16 16:02

import ckeditor.fields
from django.db import migrations, models
import toyboss.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок SEO')),
                ('description', models.TextField(blank=True, verbose_name='Описание SEO')),
                ('keywords', models.TextField(blank=True, verbose_name='Ключевые слова SEO')),
                ('page_title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
            ],
            options={
                'verbose_name': 'Общая страница О нас',
                'verbose_name_plural': 'Общая страница О нас',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'История',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('quote', models.CharField(max_length=255, verbose_name='Цитата')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Миссия',
                'verbose_name_plural': 'Миссия',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Ценности',
                'verbose_name_plural': 'Ценности',
            },
        ),
        migrations.CreateModel(
            name='ValuePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=255, verbose_name='Доверие потребителя (заголовок)')),
                ('first_text', models.TextField(verbose_name='Доверие потребителя (описание)')),
                ('second_title', models.CharField(max_length=255, verbose_name='Мы - это люди (заголовок)')),
                ('second_text', models.TextField(verbose_name='Мы - это люди (описание)')),
                ('third_title', models.CharField(max_length=255, verbose_name='На шаг впереди (заголовок)')),
                ('third_text', models.TextField(verbose_name='На шаг впереди (описание)')),
                ('fourth_title', models.CharField(max_length=255, verbose_name='Вклад в общество (заголовок)')),
                ('fourth_text', models.TextField(verbose_name='Вклад в общество (описание)')),
                ('fifth_title', models.CharField(max_length=255, verbose_name='Прозрачная и честная деятельность (заголовок)')),
                ('fifth_text', models.TextField(verbose_name='Прозрачная и честная деятельность (описание)')),
            ],
            options={
                'verbose_name': 'Пункты ценностей',
                'verbose_name_plural': 'Пункты ценностей',
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Видение',
                'verbose_name_plural': 'Видение',
            },
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255, verbose_name='Год')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Годы',
            },
        ),
    ]
