# Generated by Django 3.2.8 on 2024-06-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('left_postscript', models.CharField(blank=True, max_length=255, verbose_name='Приписка слева')),
                ('number', models.CharField(max_length=255, verbose_name='Число')),
                ('right_postscript', models.CharField(blank=True, max_length=255, verbose_name='Приписка справа')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Пункты статистики',
                'verbose_name_plural': 'Пункты статистики',
            },
        ),
    ]
