# Generated by Django 3.2.8 on 2024-06-25 10:15

from django.db import migrations, models
import django.db.models.deletion
import toyboss.functions


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_statisticpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('button_name', models.CharField(max_length=255, verbose_name='Название кнопки')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='CertificatesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=toyboss.functions.get_file_path, verbose_name='Сертификат')),
                ('certificates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_images', to='about.certificates')),
            ],
            options={
                'verbose_name': 'Изображение сертификата',
                'verbose_name_plural': 'Изображения сертификата',
            },
        ),
    ]
