# Generated by Django 3.2.8 on 2024-06-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rewards_rewardsitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
