# Generated by Django 3.2.8 on 2024-06-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_history_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='text',
        ),
        migrations.AddField(
            model_name='value',
            name='bottom_text',
            field=models.TextField(default=1, verbose_name='Верхний текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='value',
            name='top_text',
            field=models.TextField(default=1, verbose_name='Верхний текст'),
            preserve_default=False,
        ),
    ]
