# Generated by Django 3.2.8 on 2024-06-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20240625_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatesitems',
            name='description',
            field=models.TextField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatesitems',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
