# Generated by Django 3.2.8 on 2024-06-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_auto_20240626_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='description_kg',
            new_name='description_ky',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='keywords_kg',
            new_name='keywords_ky',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='page_title_kg',
            new_name='page_title_ky',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='title_kg',
            new_name='title_ky',
        ),
    ]
