# Generated by Django 3.2.8 on 2024-06-26 11:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_auto_20240626_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='years',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='years',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='years',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
    ]
