# Generated by Django 3.2.8 on 2024-06-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_auto_20240626_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='value',
            old_name='bottom_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='value',
            name='top_text',
        ),
        migrations.AddField(
            model_name='value',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Верхний текст'),
        ),
        migrations.AddField(
            model_name='value',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='Верхний текст'),
        ),
        migrations.AddField(
            model_name='value',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Верхний текст'),
        ),
        migrations.AddField(
            model_name='value',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='value',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='value',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
