# Generated by Django 3.2.8 on 2024-06-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0015_auto_20240626_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuepoints',
            name='fifth_text_en',
            field=models.TextField(null=True, verbose_name='Прозрачная и честная деятельность (описание)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='fifth_text_ky',
            field=models.TextField(null=True, verbose_name='Прозрачная и честная деятельность (описание)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='fifth_text_ru',
            field=models.TextField(null=True, verbose_name='Прозрачная и честная деятельность (описание)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='fifth_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Прозрачная и честная деятельность (заголовок)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='fifth_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Прозрачная и честная деятельность (заголовок)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='fifth_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Прозрачная и честная деятельность (заголовок)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='first_text_en',
            field=models.TextField(null=True, verbose_name='Доверие потребителя (описание)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='first_text_ky',
            field=models.TextField(null=True, verbose_name='Доверие потребителя (описание)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='first_text_ru',
            field=models.TextField(null=True, verbose_name='Доверие потребителя (описание)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='first_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Доверие потребителя (заголовок)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='first_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Доверие потребителя (заголовок)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='first_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Доверие потребителя (заголовок)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='fourth_text_en',
            field=models.TextField(null=True, verbose_name='Вклад в общество (описание)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='fourth_text_ky',
            field=models.TextField(null=True, verbose_name='Вклад в общество (описание)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='fourth_text_ru',
            field=models.TextField(null=True, verbose_name='Вклад в общество (описание)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='fourth_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Вклад в общество (заголовок)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='fourth_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Вклад в общество (заголовок)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='fourth_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Вклад в общество (заголовок)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='second_text_en',
            field=models.TextField(null=True, verbose_name='Мы - это люди (описание)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='second_text_ky',
            field=models.TextField(null=True, verbose_name='Мы - это люди (описание)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='second_text_ru',
            field=models.TextField(null=True, verbose_name='Мы - это люди (описание)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='second_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Мы - это люди (заголовок)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='second_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Мы - это люди (заголовок)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='second_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Мы - это люди (заголовок)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='third_text_en',
            field=models.TextField(null=True, verbose_name='На шаг впереди (описание)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='third_text_ky',
            field=models.TextField(null=True, verbose_name='На шаг впереди (описание)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='third_text_ru',
            field=models.TextField(null=True, verbose_name='На шаг впереди (описание)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='third_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='На шаг впереди (заголовок)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='third_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='На шаг впереди (заголовок)'),
        ),
        migrations.AddField(
            model_name='valuepoints',
            name='third_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='На шаг впереди (заголовок)'),
        ),
    ]
