# Generated by Django 3.2.8 on 2024-06-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_auto_20240626_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticpoints',
            name='left_postscript_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Приписка слева'),
        ),
        migrations.AddField(
            model_name='statisticpoints',
            name='left_postscript_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Приписка слева'),
        ),
        migrations.AddField(
            model_name='statisticpoints',
            name='left_postscript_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Приписка слева'),
        ),
        migrations.AddField(
            model_name='statisticpoints',
            name='number_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Число'),
        ),
        migrations.AddField(
            model_name='statisticpoints',
            name='number_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Число'),
        ),
        migrations.AddField(
            model_name='statisticpoints',
            name='number_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Число'),
        ),
        migrations.AddField(
            model_name='statisticpoints',
            name='right_postscript_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Приписка справа'),
        ),
        migrations.AddField(
            model_name='statisticpoints',
            name='right_postscript_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Приписка справа'),
        ),
        migrations.AddField(
            model_name='statisticpoints',
            name='right_postscript_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Приписка справа'),
        ),
        migrations.AddField(
            model_name='statisticpoints',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='statisticpoints',
            name='subtitle_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='statisticpoints',
            name='subtitle_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='statisticpoints',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='statisticpoints',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='statisticpoints',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
