# Generated by Django 3.2.8 on 2024-06-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_auto_20240626_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticpoints',
            name='number_en',
        ),
        migrations.RemoveField(
            model_name='statisticpoints',
            name='number_ky',
        ),
        migrations.RemoveField(
            model_name='statisticpoints',
            name='number_ru',
        ),
    ]
