# Generated by Django 3.2.8 on 2024-06-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_auto_20240626_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='button_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название кнопки'),
        ),
        migrations.AddField(
            model_name='certificates',
            name='button_name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название кнопки'),
        ),
        migrations.AddField(
            model_name='certificates',
            name='button_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название кнопки'),
        ),
        migrations.AddField(
            model_name='certificates',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='certificates',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='certificates',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='certificatesitems',
            name='description',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='certificatesitems',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
    ]
