# Generated by Django 3.2.8 on 2024-06-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0020_auto_20240626_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='button_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название кнопки'),
        ),
        migrations.AddField(
            model_name='rewards',
            name='button_name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название кнопки'),
        ),
        migrations.AddField(
            model_name='rewards',
            name='button_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название кнопки'),
        ),
        migrations.AddField(
            model_name='rewards',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='rewards',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='rewards',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
