# Generated by Django 3.2.8 on 2024-06-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0021_auto_20240626_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
    ]
