# Generated by Django 3.2.8 on 2024-11-17 15:11

from django.db import migrations, models
import toyboss.functions


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0023_auto_20240626_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatesitems',
            name='cert_image_184',
            field=models.ImageField(default=1, upload_to=toyboss.functions.get_file_path),
            preserve_default=False,
        ),
    ]
